{{- if and .Values.ui.enabled .Values.ui.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "horizon.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "horizon.labels" . | nindent 4 }}
  {{- with .Values.ui.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ui.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.ui.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ui.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "horizon.fullname" $ }}
                port:
                  name: http
          {{- end }}
    {{- end }}
{{- end }}
