{{- if and .Values.ui.enabled .Values.ui.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "horizon.interfaceFullname" . }}
  labels:
    {{- include "horizon.interfaceLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "horizon.interfaceFullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "horizon.interfaceIdentity" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
