apiVersion: v1
kind: Service
metadata:
  name: {{ include "horizon.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "horizon.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "horizon.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
    {{- if .Values.ui.enabled }}
    - name: http
      port: {{ .Values.service.uiPort }}
      targetPort: http
      protocol: TCP
    {{- end }}
